services:
    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profil:
        class: AppBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
