# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_BENEFICIARY: ROLE_USER
        ROLE_OBSERVATORY: ROLE_BENEFICIARY
        ROLE_AGENT: ROLE_OBSERVATORY
        ROLE_SUPER_ADMIN: ROLE_AGENT
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                success_handler: app.security.login_success_handler
            logout:
                path: fos_user_security_logout
                target: /
                handlers: [app.security.logout_handler]
                invalidate_session: false
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/connexion$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-perdu, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_OBSERVATORY }
        - { path: ^/admin/log, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/type-evenement, roles: ROLE_SUPER_ADMIN }
        - { path: ^/$, roles: ROLE_BENEFICIARY }
