parameters:
    smart.host_env: dev
    smart.project_domain: billetterie.sf
    smart.project_url: https://billetterie.sf/
    smart.project_name: billetterie
    smart.project_title: billetterie
    smart.vagrant_ip: 192.168.33.33
    smart.email_sender_name: billetterie
    smart.developer_email: "%smart_developer_email%"
    smart.contact_email: "%smart_contact_email%"

smart_user:
    model:
        user_class: AppBundle\Entity\User
